//! Shared types for RadioDoge.
//!
//! All types derive Serialize/Deserialize so they can be sent
//! over Tauri IPC to the Svelte frontend or printed from the CLI.

use serde::{Deserialize, Serialize};

/// LoRa radio statistics — updated every 2 seconds when connected.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RadioStats {
    /// Frequency in MHz (e.g. 915.0)
    pub frequency_mhz: f32,
    /// TX power in dBm (5–20)
    pub power_dbm: i8,
    /// LoRa spreading factor (7–12)
    pub spreading_factor: u8,
    /// Bandwidth in kHz (125, 250, or 500)
    pub bandwidth_khz: f32,
    /// Coding rate string (e.g. "4/5")
    pub coding_rate: String,
    /// Last received RSSI in dBm (typically -50 to -120)
    pub rssi: i16,
    /// Last received SNR in dB
    pub snr: f32,
    /// Total packets sent this session
    pub packets_sent: u32,
    /// Total packets received this session
    pub packets_received: u32,
}

impl Default for RadioStats {
    fn default() -> Self {
        RadioStats {
            frequency_mhz: 915.0,
            power_dbm: 5,
            spreading_factor: 7,
            bandwidth_khz: 125.0,
            coding_rate: "4/5".to_string(),
            rssi: -120,
            snr: 0.0,
            packets_sent: 0,
            packets_received: 0,
        }
    }
}

/// RadioDoge mesh network address: Region.Community.Node
/// Example: 10.0.2 means Region=10, Community=0, Node=2
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NodeAddress {
    pub region: u8,
    pub community: u8,
    pub node: u8,
}

impl NodeAddress {
    pub fn new(region: u8, community: u8, node: u8) -> Self {
        NodeAddress { region, community, node }
    }

    /// Broadcast address: 255.255.255
    pub fn broadcast() -> Self {
        NodeAddress { region: 0xFF, community: 0xFF, node: 0xFF }
    }

    /// Default local address: 10.0.1
    pub fn default_local() -> Self {
        NodeAddress { region: 10, community: 0, node: 1 }
    }

    pub fn to_display_string(&self) -> String {
        format!("{}.{}.{}", self.region, self.community, self.node)
    }
}

impl Default for NodeAddress {
    fn default() -> Self {
        NodeAddress::default_local()
    }
}

/// Dogecoin wallet information generated by the app.
/// The private key is in WIF format (starts with "Q" for mainnet compressed).
/// ⚠️  NEVER log or transmit the private key!
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WalletInfo {
    /// Dogecoin address, starts with "D" on mainnet
    pub address: String,
    /// Compressed public key as hex string (66 chars)
    pub public_key_hex: String,
    /// Private key in WIF format (starts with "Q" for compressed mainnet)
    pub private_key_wif: String,
}

/// LoRa configuration parameters sent to the Heltec device.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoraSettings {
    pub frequency_mhz: f32,
    pub power_dbm: i8,
    pub spreading_factor: u8,
    pub bandwidth_khz: f32,
    pub coding_rate: String,
    pub node_address: NodeAddress,
}

impl Default for LoraSettings {
    fn default() -> Self {
        LoraSettings {
            frequency_mhz: 915.0,
            power_dbm: 5,
            spreading_factor: 7,
            bandwidth_khz: 125.0,
            coding_rate: "4/5".to_string(),
            node_address: NodeAddress::default_local(),
        }
    }
}

/// A transaction request from the Send tab.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransactionRequest {
    /// Recipient Dogecoin address
    pub to_address: String,
    /// Amount in DOGE
    pub amount_doge: f64,
    /// Optional memo (sent in LoRa packet payload)
    pub memo: Option<String>,
    /// Sender's WIF private key (from generated wallet)
    pub from_private_key_wif: Option<String>,
}

/// An incoming LoRa packet captured by the receive loop.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IncomingPacket {
    /// Unix timestamp (seconds)
    pub timestamp: u64,
    /// Source node address
    pub source: NodeAddress,
    /// Destination node address
    pub destination: NodeAddress,
    /// Command type byte
    pub command: u8,
    /// Raw payload as hex string
    pub payload_hex: String,
    /// Human-readable decoded content (if parseable)
    pub decoded: Option<String>,
    /// RSSI of this packet in dBm
    pub rssi: i16,
}

/// v0.3.6 — Board-is-source-of-truth: live state reported by the Heltec device
/// on CMD_GET_SETTINGS (0x22) response.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BoardSettings {
    /// Node address as currently stored in the board's NVS flash
    pub node_address: NodeAddress,
    /// Whether the board is in gateway mode (persisted across power cycles)
    pub gateway_mode: bool,
    /// v0.3.7 — Whether the WiFi radio is enabled (persisted, default true)
    #[serde(default = "default_true")]
    pub wifi_enabled: bool,
}

fn default_true() -> bool { true }

/// v0.3.7 — A recently heard mesh neighbor.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NeighborEntry {
    /// The neighbor's node address
    pub address: NodeAddress,
    /// Last heard RSSI in dBm
    pub rssi: i16,
    /// Unix timestamp (seconds) of last heard packet
    pub last_seen: u64,
}

/// v0.3.6 — Transaction history entry (kept in app-local JSON, last 50 entries).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TxHistoryEntry {
    /// Unix timestamp (seconds) when the TX was initiated
    pub timestamp: u64,
    /// Recipient Dogecoin address
    pub to_address: String,
    /// Amount in DOGE
    pub amount_doge: f64,
    /// Optional memo
    pub memo: Option<String>,
    /// TX status: "sent", "failed"
    pub status: String,
}

/// Information about a serial port visible to the OS.
///
/// Returned by `list_ports_with_info()` so the UI can display friendly names,
/// prioritise USB serial devices, and flag ports that match known Heltec/ESP32 adapters.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PortInfo {
    /// OS-level port name (e.g. "COM3" on Windows, "/dev/ttyUSB0" on Linux)
    pub name: String,
    /// True if this is a USB serial adapter (vs. a native COM/PCI port)
    pub is_usb: bool,
    /// USB manufacturer string, if reported by the adapter
    pub manufacturer: Option<String>,
    /// USB product string, if reported by the adapter (e.g. "CP2102 USB to UART Bridge")
    pub product: Option<String>,
    /// USB Vendor ID in decimal (Silicon Labs = 4292, Jiangsu Qinheng = 6790)
    pub vid: Option<u16>,
    /// USB Product ID in decimal
    pub pid: Option<u16>,
    /// Short human-readable label for display (e.g. "COM3 — CP2102 USB to UART Bridge")
    pub description: String,
    /// True if this port matches a USB VID/PID known to be used by Heltec / ESP32 boards
    pub is_likely_heltec: bool,
}

/// Connection status — emitted as a Tauri event.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "message")]
pub enum ConnectionStatus {
    Disconnected,
    Connecting,
    Connected,
    Error(String),
}

/// Wrapper for connection status events to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionStatusEvent {
    pub status: String,
    pub port: Option<String>,
    pub node_address: Option<NodeAddress>,
    pub message: Option<String>,
    /// Firmware version string reported by the Heltec device, e.g. "v1.2.3"
    pub firmware_version: Option<String>,
}

impl ConnectionStatusEvent {
    pub fn disconnected() -> Self {
        ConnectionStatusEvent {
            status: "disconnected".to_string(),
            port: None,
            node_address: None,
            message: None,
            firmware_version: None,
        }
    }

    pub fn connecting(port: &str) -> Self {
        ConnectionStatusEvent {
            status: "connecting".to_string(),
            port: Some(port.to_string()),
            node_address: None,
            message: None,
            firmware_version: None,
        }
    }

    pub fn connected(port: &str, addr: NodeAddress, firmware_version: Option<String>) -> Self {
        ConnectionStatusEvent {
            status: "connected".to_string(),
            port: Some(port.to_string()),
            node_address: Some(addr),
            message: None,
            firmware_version,
        }
    }

    pub fn reconnecting(port: &str) -> Self {
        ConnectionStatusEvent {
            status: "reconnecting".to_string(),
            port: Some(port.to_string()),
            node_address: None,
            message: None,
            firmware_version: None,
        }
    }

    pub fn error(msg: &str) -> Self {
        ConnectionStatusEvent {
            status: "error".to_string(),
            port: None,
            node_address: None,
            message: Some(msg.to_string()),
            firmware_version: None,
        }
    }
}
